### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [jaymherrmann/colmaracademy#6]
Grade: Satisfactory

Summary: Nice job on this project, it looks good on desktop and mobile. You used a lot of good techniques and kept your code organized. Take a look at the issues I created as they will help you organize your code a bit. Your transitions look really good. I would work on making that nav bar look right on mobile and then you should have a pretty solid site.
Overall great job, hope you enjoyed the course.

**Comment by jaymherrmann** [comment]
Thanks rimmesbe. Some great and really helpful feedback. Cheers, Jay
